name: Deploy Frontend (S3 + CloudFront)

on:
  push:
    branches: [main, dev]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      ENV: ${{ github.ref == 'refs/heads/main' && 'PROD' || 'DEV' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install deps
        working-directory: frontend
        run: npm ci

      - name: Build Vite (inject API URL)
        working-directory: frontend
        run: |
          echo "VITE_API_URL=${{ secrets[format('API_BASE_{0}', env.ENV)] }}" > .env
          npm run build

      - name: Sync to S3
        run: |
          aws s3 sync frontend/dist s3://${{ secrets[format('FE_BUCKET_{0}', env.ENV)] }} --delete

      - name: Invalidate CloudFront
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets[format('CF_DIST_{0}', env.ENV)] }} \
            --paths "/*"
