name: Deploy Backend (Lambda)

on:
  push:
    branches: [main, dev]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CONFIG_ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2

      - name: Debug files
        working-directory: backend
        run: |
          node -v
          npm -v
          pwd
          ls -la
          head -n 20 package.json
          head -n 40 package-lock.json

      - name: Install backend deps
        working-directory: backend
        env:
          NODE_ENV: "" # ensure dev deps aren't implicitly omitted by env
        run: |
          npm install --omit=dev --no-audit --no-fund

      - name: SAM build
        working-directory: backend
        run: sam build --cached

      - name: Who am I / region
        run: |
          aws sts get-caller-identity
          aws configure list

      - name: SAM deploy (explicit)
        working-directory: backend
        env:
          STACK_NAME: med-arb-api-${{ env.CONFIG_ENV }}
        run: |
          sam deploy \
            --template-file template.yaml \
            --stack-name "$STACK_NAME" \
            --resolve-s3 \
            --region "$AWS_REGION" \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              EnvName=${{ env.CONFIG_ENV }} \
              FrontendOrigin=${{ secrets[format('FE_ORIGIN_{0}', env.CONFIG_ENV == 'prod' && 'PROD' || 'DEV')] }} \
              JwtSecret=${{ secrets[format('JWT_SECRET_{0}', env.CONFIG_ENV == 'prod' && 'PROD' || 'DEV')] }} \
              MongoUrl=${{ secrets[format('MONGO_URL_{0}', env.CONFIG_ENV == 'prod' && 'PROD' || 'DEV')] }} \
              GoogleClientId=${{ secrets.GOOGLE_CLIENT_ID }} \
              GoogleClientSecret=${{ secrets.GOOGLE_CLIENT_SECRET }} \
              GoogleRedirectUri=${{ secrets[format('GOOGLE_REDIRECT_URI_{0}', env.CONFIG_ENV == 'prod' && 'PROD' || 'DEV')] }}

          echo "---- Stack outputs ----"
          aws cloudformation describe-stacks \
            --region "$AWS_REGION" \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='ApiBaseUrl'].OutputValue" \
            --output text
