name: Deploy Backend (Lambda)

on:
  push:
    branches: [main, dev]

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      CONFIG_ENV: ${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      STACK_NAME: med-arb-api-${{ github.ref == 'refs/heads/main' && 'prod' || 'dev' }}
      ENV_SUFFIX: ${{ github.ref == 'refs/heads/main' && 'PROD' || 'DEV' }}

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
          cache-dependency-path: backend/package-lock.json

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOY_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Install SAM CLI
        uses: aws-actions/setup-sam@v2

      # If a previous deploy left the stack in ROLLBACK_COMPLETE, delete it first
      - name: Nuke stuck stack (ROLLBACK_COMPLETE)
        run: |
          set -euo pipefail
          STATUS=$(aws cloudformation describe-stacks \
            --region "$AWS_REGION" \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].StackStatus" --output text 2>/dev/null || echo "NOT_FOUND")
          echo "Current stack status: $STATUS"
          if [ "$STATUS" = "ROLLBACK_COMPLETE" ]; then
            echo "Deleting stuck stack $STACK_NAME..."
            aws cloudformation delete-stack --region "$AWS_REGION" --stack-name "$STACK_NAME"
            aws cloudformation wait stack-delete-complete --region "$AWS_REGION" --stack-name "$STACK_NAME"
          fi

      - name: SAM build
        working-directory: backend
        run: sam build --cached

      # (Optional) artifact bucket ensure
      - name: Ensure artifact bucket
        env:
          ARTIFACT_BUCKET: ${{ secrets[format('SAM_ARTIFACT_BUCKET_{0}', env.ENV_SUFFIX)] }}
        run: |
          set -euo pipefail
          echo "Ensuring artifacts bucket exists: $ARTIFACT_BUCKET (region $AWS_REGION)"
          if ! aws s3api head-bucket --bucket "$ARTIFACT_BUCKET" 2>/dev/null; then
            aws s3api create-bucket --bucket "$ARTIFACT_BUCKET"   # us-east-1 => no LocationConstraint
            aws s3api put-bucket-versioning --bucket "$ARTIFACT_BUCKET" --versioning-configuration Status=Enabled
          fi

      - name: SAM deploy
        working-directory: backend
        env:
          ARTIFACT_BUCKET: ${{ secrets[format('SAM_ARTIFACT_BUCKET_{0}', env.ENV_SUFFIX)] }}
          FRONTEND_ORIGIN: ${{ secrets[format('FE_ORIGIN_{0}', env.ENV_SUFFIX)] }}
          JWT_SECRET: ${{ secrets[format('JWT_SECRET_{0}', env.ENV_SUFFIX)] }}
          MONGO_URL: ${{ secrets[format('MONGO_URL_{0}', env.ENV_SUFFIX)] }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          GOOGLE_REDIRECT_URI: ${{ secrets[format('GOOGLE_REDIRECT_URI_{0}', env.ENV_SUFFIX)] }}
        run: |
          set -euo pipefail
          sam deploy \
            --debug \
            --template-file template.yaml \
            --stack-name "$STACK_NAME" \
            --s3-bucket "$ARTIFACT_BUCKET" \
            --region "$AWS_REGION" \
            --capabilities CAPABILITY_IAM \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              EnvName="$CONFIG_ENV" \
              FrontendOrigin="$FRONTEND_ORIGIN" \
              JwtSecret="$JWT_SECRET" \
              MongoUrl="$MONGO_URL" \
              GoogleClientId="$GOOGLE_CLIENT_ID" \
              GoogleClientSecret="$GOOGLE_CLIENT_SECRET" \
              GoogleRedirectUri="$GOOGLE_REDIRECT_URI"

      - name: Show ApiBaseUrl output & smoke test
        env:
          STACK_NAME: ${{ env.STACK_NAME }}
        run: |
          set -euo pipefail
          API_URL=$(aws cloudformation describe-stacks \
            --region "$AWS_REGION" \
            --stack-name "$STACK_NAME" \
            --query "Stacks[0].Outputs[?OutputKey=='ApiBaseUrl'].OutputValue" \
            --output text)
          echo "ApiBaseUrl: $API_URL"

          echo "Smoke: /health"
          curl -fsS "$API_URL/health" && echo "OK"

          echo "Smoke: /db-ping (allowed to fail in dev if Atlas blocks)"
          curl -fsS "$API_URL/db-ping" || echo "db-ping failed (likely Atlas allowlist/VPC)"
